import numpy as np
import numpy.typing as npt
import pandas as pd
import json

from .campaign_manager import CampaignManager
from .session_generator import SessionGenerator
from .interaction_generator import InteractionGenerator

from src.utils import present_line, DATE_FORMAT
from src import utils

DEFAULT_CONFIG = {
    "random_seed": 42,
    "day_bias_enabled": False,
    "base_growth_rate": 0.01,
    "new_campaign_probability": 0.1,
    "trend_noise_ratio": 0.02,
    "campaign": {
        "speed": {"min": -10, "max": 11},
        "duration_months": {"min": 1, "max": 12},
        "pageview_prob_range": {"min": 0, "max": 1},
        "visit_shape": {"min": 1, "max": 3},
        "visit_duration": {"min": 1, "max": 30},
        "visit_min_duration": {"min": 1, "max": 5},
        "click_shape": {"min": 0.5, "max": 1},
        "click_min_per_page": {"min": 0, "max": 4},
        "day_bias_sd": 0.25
    }
}

class DataGenerator():

    """
    Generator class for generating sample data.
    """

    def __init__(
            self,
            config: dict = None,
            seed: int = 42,
            day_bias = False
        ):
        self._rng = np.random.default_rng(seed)
        if config == None:
            self.config = DEFAULT_CONFIG
        else:
            self.config = config

        self._default_campaign = {
            "id": np.array([], dtype=int), # id of the campaign
            "session": {"reach": [], "skew": [], "loc": [], "scale": [], "day_bias": np.empty((0,7))}, # Properties of session trends per campaign
            "click": {"shape": [], "avg_click": [], "min_click": []}, # Properties of clicktrend per campaign
            "pageview": {"p": []}, # Probability of visiting another page per campaign
            "duration": {"shape": [], "avg_duration": [], "min_duration": []} # properties of the durations 
        }

        # Initialize default state values
        if "campaign" not in self.state:
            self.state["campaign"] = self._default_campaign.copy()

        self.campaign_manager = CampaignManager(self._rng, self.state['campaign'], self.config)
        self.session_generator = SessionGenerator(self._rng, self.state['campaign']['session'], self.config, day_bias)
        self.interaction_generator = InteractionGenerator(self._rng, self.state["max_page_views"], self.state["max_clicks"], 
                                                          self.config["campaign"]["visit_duration"]["max"], self.state["campaign"], config)

    def _load_state(self, state_path = "config/state.json"):
        """
        Load state from file and convert to numpy arrays.
        """
        try:
            self.state = utils.load_json(state_path)
        except FileNotFoundError:
            present_line("Please make sure you have generated initial data before running update.")
            exit(1)
        self.state = utils.dict_list_to_ndarray(self.state)
        self.state["campaign"]["session"]["loc"] = self.state["campaign"]["session"]["loc"].astype('datetime64[D]').astype(np.int64)
        return self.state

    def _save_state(self, state_path = "config/state.json"):
        """
        Write the updated state to file.
        """
        # Convert campaign properties to lists for json conversion
        self.state["campaign"]["session"]["loc"] = self.state["campaign"]["session"]["loc"].astype('datetime64[D]').astype(str)
        self.state = utils.dict_ndarray_to_list(self.state)

        # write state to file
        with open(state_path, 'w') as file:
            json.dump(self.state, file, indent=4)

    def _sort_by_date(self, ids: npt.NDArray[np.integer], dates: npt.NDArray[np.datetime64]) -> tuple[npt.NDArray[np.integer], npt.NDArray[np.datetime64]]:
        """
        Sort dates together with its campaign_ids.

        :param ids: ids that are coupled with the dates
        :param dates: dates to be sorted

        :return: sorted ids, sorted dates
        """
        # Get the indexorder of the sorted array
        idx = np.argsort(dates)

        # Sort the arrays
        sorted_ids = ids[idx]
        sorted_dates = dates[idx]

        return sorted_ids, sorted_dates

    def generate_data(self, n_campaign_records: int, n_base_records: int, start: int, end: np.int64) -> dict[str, npt.NDArray]:
        """ 
        Main generator function.
        This function generates data from `start` to `end`.
        
        `n_campaign_records` records are generated from a campaign and `n_base_records` 
        are generated from a base trend that grows independent of campaigns.

        :param n_campaign_records: number of records belonging to a campaign to generate
        :param n_base_records: number of base records to generate, not generated by a campaign
        :param start: start date of record generation
        :param end: end date of record generation
        :return: generated data as dictionary
        """
        number_of_records = n_campaign_records + n_base_records

        # Unique session ID
        old_records = self.state.get("last_record", 0)
        session_ids = np.arange(old_records + 1, old_records + number_of_records + 1)

        # A visitor may be recurrent. Therefore the possibility for duplicate IDs is needed
        visitor_ids = self._rng.integers(1, number_of_records * 3, number_of_records)

        # Sample campaign ids
        campaign_ids = self.campaign_manager.sample_campaign_ids(n_campaign_records, start, end)

        # Generate random dates and sort for chronological order of sessions
        session_dates = self.session_generator.generate_sessions(campaign_ids, n_campaign_records, start, end)

        # Generate base trend
        base_session_dates = self.session_generator.generate_base(start, end, n_base_records)
        session_dates = np.concatenate([session_dates, base_session_dates])
        campaign_ids = np.concatenate([campaign_ids, np.zeros(n_base_records, dtype=int)])

        # Sort for chronology
        campaign_ids, session_dates = self._sort_by_date(campaign_ids, session_dates)

        # Generate interactions (clicks, page views, durations)
        visit_duration, view_total, click_total = self.interaction_generator.generate_interaction(campaign_ids, number_of_records)

        conversion = self.interaction_generator.generate_conversion(click_total, view_total, visit_duration, number_of_records)

        # Generate random source data
        randomized_device = self._rng.integers(1, self.state['max_devices'], number_of_records)

        randomized_city = self._rng.integers(1, self.state['max_location'], number_of_records)

        randomized_traffic_sources = self._rng.integers(1, self.state['max_traffic_sources'], number_of_records)

        randomized_country = self._rng.choice(self.state['country'], number_of_records)

        # Calculate new state
        last_day = session_dates[-1].astype("datetime64[D]")
        date_mask = session_dates.astype("datetime64[D]") == last_day
        campaign_ids_last_day = campaign_ids[date_mask]

        records_per_campaign = np.bincount(
            campaign_ids_last_day,
            minlength=1 + len(self.state["campaign"]["id"])
        )

        # Update state
        self.state["records_last_day"] = int(campaign_ids_last_day.size)
        self.state["records_last_day_per_campaign"] = records_per_campaign

        self.state["last_record"] = old_records + number_of_records
        self.state["current_date"] = end.astype('datetime64[D]').item().strftime(DATE_FORMAT)

        generated_records = {
            "sessie_ID": session_ids,
            "campagne_ID": campaign_ids,
            "bezoeker_ID": visitor_ids,
            "starttijd_bezoek": session_dates,
            "eindtijd_bezoek": (session_dates + visit_duration),
            "totale_tijd_bezoek": visit_duration.astype(int),
            "kliks_op_site_elementen": click_total.astype(int),
            "paginas_bekeken": view_total.astype(int),
            "apparaat": randomized_device,
            "land": randomized_country,
            "stad": randomized_city,
            "verkeers_bron": randomized_traffic_sources,
            "conversie": conversion.astype(int)
        }

        if len(generated_records["sessie_ID"]) != number_of_records:
            present_line("Something went wrong!")
            present_line("The number of records generated doesn't equal the number of records needed.")

        return generated_records

    def save_data(self, data: pd.DataFrame, save_path: str, sep: str = ';', date_format="%d-%m-%Y %H:%M"):
        """
        Saves generated records to file.

        :param data:
        :param save_path:
        :param sep:
        :param date_format:
        """
        present_line("Saving records..")

        # Append to file when updating
        write_mode = 'a' if self.update else 'w'

        data.to_csv(
            save_path, 
            sep=sep, 
            date_format=date_format, 
            mode=write_mode, 
            index=False, 
            header=not self.update
        )

        # Save the current state to file
        self._save_state()

        present_line("Records saved")
        present_line("\nHave a pretty day!\n")