"""Central, configuration-driven eligibility for hiring and career moves."""
import pandas as pd

from src.infrastructure.employment_history import employment_history_for

LEVELS = {"Geen": 0, "MBO": 1, "HBO": 2, "WO": 3, "PhD": 4}


def _value(row, name, default=None):
    """Read a role requirement while keeping older narrow fixtures usable."""
    value = row.get(name, default)
    return default if pd.isna(value) else value


def _role_requirements(config, role_name):
    return getattr(config, "role_career_paths", {}).get(role_name, {})


def _credential_rows(credentials):
    """Normalise external candidate credentials to name/level dictionaries."""
    if not credentials:
        return []
    if isinstance(credentials, pd.DataFrame):
        return credentials.to_dict("records")
    return list(credentials)


def _matching_credentials(config, target_role, credentials):
    required = set(_role_requirements(config, target_role["Functie_Naam"])
                   .get("relevante_opleidingen", []))
    return [
        credential for credential in _credential_rows(credentials)
        if credential.get("Opleiding_Naam") in required
    ]


def _required_relevant_experience(config, target_role, credentials):
    """Apply the configured experience requirement, including the WO senior rule."""
    required = float(_value(target_role, "Min_Relevante_Ervaring_Jr", 0.0))
    if not str(_value(target_role, "Functie_Naam", "")).startswith("Senior "):
        return required

    matches = _matching_credentials(config, target_role, credentials)
    has_relevant_wo = any(
        LEVELS.get(credential.get("Opleidingsniveau"), 0) >= LEVELS["WO"]
        for credential in matches
    )
    return min(required, 2.0) if has_relevant_wo else required


def external_rejection_reason(config, target_role, candidate_profile):
    """Return why an external candidate fails the role's eligibility policy,
    or None if they pass.

    Mirrors `eligible_external`'s checks in the same order, so the reported
    reason is always the first requirement the candidate actually failed -
    derived from the same policy that gates the offer, not an independently
    sampled label sitting alongside it.
    """
    credentials = candidate_profile.get("Qualifications", [])
    matches = _matching_credentials(config, target_role, credentials)
    min_level = LEVELS.get(_value(target_role, "Min_Opleidingsniveau", "Geen"), 0)
    has_required_qualification = any(
        LEVELS.get(credential.get("Opleidingsniveau"), 0) >= min_level
        for credential in matches
    )
    formal_required = bool(_value(
        target_role, "Formele_Kwalificatie_Vereist", False
    ))
    if formal_required and not has_required_qualification:
        return "Opleiding of kwalificatie onvoldoende"

    experience = float(candidate_profile.get("Relevante_Ervaring_Jaren", 0.0))
    if experience < _required_relevant_experience(
        config, target_role, credentials
    ):
        return "Onvoldoende relevante werkervaring"

    if bool(_value(target_role, "Leidinggevend", False)):
        leadership = float(candidate_profile.get(
            "Leidinggevende_Ervaring_Jaren", 0.0
        ))
        if leadership < float(_value(
            target_role, "Min_Leidinggevende_Ervaring_Jr", 0.0
        )):
            return "Onvoldoende leidinggevende ervaring"
    return None


def eligible_external(config, target_role, candidate_profile):
    """Return whether a pre-offer external candidate meets the role policy.

    Candidate profiles deliberately carry real years and credentials rather
    than relying on the reporting-only 1--5 quality scores.  The profile is
    generated by recruitment and is then passed unchanged to hiring.
    """
    return external_rejection_reason(config, target_role, candidate_profile) is None

def movement_type(config, source_name, target_name):
    path = config.role_career_paths.get(source_name, {})
    if target_name in path.get("logische_doorgroei", []): return "Promotie"
    if target_name in path.get("laterale_transfers", []): return "Transfer"
    return None

def credentials_for(state, employee_key, date):
    rows = state.get("fact_employee_qualification", pd.DataFrame())
    if rows.empty: return set()
    rows = rows[(rows.Employee_Key == employee_key) & (pd.to_datetime(rows.Behaald_Datum) <= pd.Timestamp(date))]
    lookup = state["dim_education"].set_index("Education_Key")["Opleiding_Naam"]
    return set(rows.Education_Key.map(lookup).dropna())

def relevant_experience(state, employee_key, target_role, date, config=None):
    history = employment_history_for(state, employee_key)
    roles = state["dim_role"].set_index("Role_Key")
    target = target_role["Functie_Naam"]
    allowed = {target}
    for source, cfg in (getattr(config, "role_career_paths", {}) if config else {}).items():
        if target in cfg.get("logische_doorgroei", []) or target in cfg.get("laterale_transfers", []): allowed.add(source)
    total=0.0
    for _, row in history.iterrows():
        if roles.loc[row.Role_Key, "Functie_Naam"] not in allowed: continue
        end=pd.Timestamp(row.Einddatum) if pd.notna(row.Einddatum) else pd.Timestamp(date)
        start=pd.Timestamp(row.Startdatum)
        total += max(0,(min(end,pd.Timestamp(date))-start).days/365.2425)
    return total

def eligible_internal(config, state, employee_key, source_role, target_role, date, performance=3.0):
    target_name=target_role["Functie_Naam"]
    kind=movement_type(config, source_role["Functie_Naam"], target_name)
    if not kind or performance < 2.7: return False
    if kind == "Transfer" and source_role.SalaryScale_Key != target_role.SalaryScale_Key: return False
    exp=relevant_experience(state,employee_key,target_role,date,config)
    if exp < float(target_role.Min_Relevante_Ervaring_Jr): return False
    required=set(config.role_career_paths[target_name].get("relevante_opleidingen", []))
    has=credentials_for(state,employee_key,date)
    if bool(target_role.Formele_Kwalificatie_Vereist) and required and not has.intersection(required): return False
    # first line-management move has an explicit three-year internal exception
    if bool(target_role.Leidinggevend) and not bool(source_role.Leidinggevend) and exp < 3: return False
    return True
